Feat/auth methods
IBM/unity-sdk-core pull request #15
Opened 2019-08-26 02:53 UTC by mamoonraja

This pull request updates authentication to use Authenticators rather than AuthConfigs. Additionally, legacy authentication logic was removed. Changes to the core essentially followed changes to the [java sdk core](https://github.com/IBM/java-sdk-core/pull/51). I have tested changes with IAM, will do some more testing on other methods, and especially for `WSConnector`.

We are using branch 1.0.0-rc to stage major release changes. Below is the new snippet for authentication:

```cs
IamAuthenticator authenticator = new IamAuthenticator("{apikey}");
AssistantService service = new AssistantService("{versionDate}", authenticator);
```

Following changes to respective service files will be needed:

Constructors:

```cs
public AssistantService(string versionDate) : this(versionDate, ConfigBasedAuthenticatorFactory.GetAuthenticator(serviceId)) { }

public AssistantService(string versionDate, Authenticator authenticator) : base(versionDate, authenticator, serviceId)
```

In method:

```cs
            RESTConnector connector = RESTConnector.GetConnector(authenticator, "/v1/workspaces");
            if (connector == null)
            {
                return false;
            }

            authenticator.Authenticate(connector);
            return connector.Send(req);
```

2019-08-26 16:09 UTC, mediumTaj requested changes
I think this is coming together! A few questions here. We prob can get rid of some constructors in the base service. What do you think about moving adding headers to the connectors in the form of `WithAuthentication` methods?

2019-08-26 16:09 UTC, mediumTaj commented on Authentication/Authenticator.cs
> +        public string Password { get; private set; }
Do we need these three props in the base authenticator?

2019-08-26 16:09 UTC, mediumTaj commented on Authentication/Authenticator.cs
> +        }
Do we need this method in the base authenticator?

2019-08-26 16:09 UTC, mediumTaj commented on Authentication/BasicAuthenticator.cs
> +            connector.Headers.Add("Authorization", Utility.CreateAuthorization(Username, Password));
Should this happen in `RESTConnector` and `WSConnector` instead of adding headers directly to the connector? Possibly with the following methods in each connector?

```cs
public void WithAuthentication(string username, string password);
public void WithAuthentication(string bearerToken);
```

2019-08-26 16:09 UTC, mediumTaj commented on Authentication/Iam/IamAuthenticator.cs
> +        private readonly string defaultUrl = "https://iam.cloud.ibm.com/identity/token";
We can probably remove this and use `DefaultIamUrl`. I didn't realize i had this twice in .NET.

2019-08-26 16:09 UTC, mediumTaj commented on Authentication/Iam/IamAuthenticator.cs
> +                url = defaultUrl;
Can prob use `DefaultIamUrl` here

2019-08-26 16:09 UTC, mediumTaj commented on BaseService.cs
> +        public static string propnameDisableSsl = "DISABLE_SSL";
rename to `PropNameServiceDisableSslVerification` since this is a service level and we don't want to confuse with `PropNameDisableSslVerification`

2019-08-26 16:09 UTC, mediumTaj commented on BaseService.cs
> +        protected string Url;
protected/private member variables should be lowerCamelCase (`url`)

2019-08-26 16:09 UTC, mediumTaj commented on BaseService.cs
> +        }
Are we ever using this constructor? I think we only use 
```cs
BaseService(versionDate, authenticator, serviceId)
BaseService(authenticator, serviceId)
```

2019-08-26 16:09 UTC, mediumTaj commented on BaseService.cs
> +        public BaseService(string versionDate, string serviceId) : this(serviceId) { }
Are we ever using this constructor? I think we only use 
```cs
BaseService(versionDate, authenticator, serviceId)
BaseService(authenticator, serviceId)
```

2019-08-26 16:09 UTC, mediumTaj commented on BaseService.cs
> +            // DisableSslVerification(disableSsl);
Are we doing this check anywhere else?

2019-08-26 16:09 UTC, mediumTaj commented on BaseService.cs
> +        }
What will we be using this constructor for?

2019-08-26 16:09 UTC, mediumTaj commented on Connection/WSConnector.cs
> +            else if (authenticator.AuthenticationType == "iam" || authenticator.AuthenticationType == "cp4d")
Can we use `Authenticator.AuthTypeIam` and `Authenticator.AuthTypeCp4d` here instead of the string values?

2019-08-26 16:09 UTC, mediumTaj commented on Connection/WSConnector.cs
> +                authenticator.Authenticate(connector);
Should this happen in WSConnector or in the service? Is there anywhere to call this from the service?

2019-08-26 17:18 UTC, mamoonraja commented on Authentication/Authenticator.cs
> +        public string Password { get; private set; }
I put them in there because `WSConnector` looks for them, I am finishing off `WSConnector` so based on that I will remove this.

2019-08-26 17:20 UTC, mamoonraja commented on Authentication/Authenticator.cs
> +        }
I think we can get rid of this one.

2019-08-26 17:21 UTC, mamoonraja commented on Authentication/BasicAuthenticator.cs
> +            connector.Headers.Add("Authorization", Utility.CreateAuthorization(Username, Password));
you mean something like:

```
connector.withAuthentication(...)
```

and we update the headers locally?

2019-08-26 17:23 UTC, mamoonraja commented on BaseService.cs
> +        protected string Url;
good catch!

2019-08-26 17:25 UTC, mamoonraja commented on BaseService.cs
> +        }
this one is for when there is no authenticator provided and we use `ConfigBasedAuthenticatorFactory`. Integration tests are using this one right now, eg:

```cs
                service = new AssistantService(versionDate);
```

2019-08-26 17:27 UTC, mamoonraja commented on BaseService.cs
> +        }
On second thought, we can use that at the service level too.

2019-08-26 18:08 UTC, mediumTaj commented on Authentication/BasicAuthenticator.cs
> +            connector.Headers.Add("Authorization", Utility.CreateAuthorization(Username, Password));
```cs
connector.WithAuthentication(...)
```

Yeah set the headers inside `WithAuthentication()` - what do you think?

2019-08-26 18:23 UTC, mamoonraja commented on Authentication/BasicAuthenticator.cs
> +            connector.Headers.Add("Authorization", Utility.CreateAuthorization(Username, Password));
Sounds good!

2019-08-26 21:05 UTC, mamoonraja commented on Authentication/Authenticator.cs
> +        }
Using `CanAuthenticate` instead of `HasTokenData`

2019-08-27 12:48 UTC, mamoonraja commented on Connection/WSConnector.cs
> +                authenticator.Authenticate(connector);
moving it to service.

2019-08-27 18:33 UTC, mediumTaj approved these changes
👍 looks good - just a few minor changes. Approving now though.

2019-08-27 18:33 UTC, mediumTaj commented on Utilities/Utility.cs
> +            double.TryParse(input, out output);
collapse these two lines
```cs
double.TryParse(input, out double output);
```

2019-08-27 18:33 UTC, mediumTaj commented on Connection/WSConnector.cs
> +        public void WithAuthentication(string username, string password)
Params in the comment are wrong

2019-08-27 18:33 UTC, mediumTaj commented on Connection/WSConnector.cs
> +        public void WithAuthentication(string bearerToken)
Params in the comment are wrong

2019-08-27 18:33 UTC, mediumTaj commented on Connection/RESTConnector.cs
> +            Headers.Add("Authorization", Utility.CreateAuthorization(username, password));
we can use `AUTHENTICATION_AUTHORIZATION_HEADER` here

2019-08-27 18:33 UTC, mediumTaj commented on Connection/RESTConnector.cs
> +            Headers.Add("Authorization", string.Format("Bearer {0}", bearerToken));
we can use `AUTHENTICATION_AUTHORIZATION_HEADER` here

2019-08-27 18:33 UTC, mediumTaj commented on Connection/RESTConnector.cs
> +        public void WithAuthentication(string bearerToken)
Params in the comment are wrong

2019-08-27 18:33 UTC, mediumTaj commented on Connection/RESTConnector.cs
> +        public void WithAuthentication(string username, string password)
Params in the comment are wrong

2019-08-27 18:33 UTC, mediumTaj commented on Connection/WSConnector.cs
> +            Headers.Add("Authorization", string.Format("Bearer {0}", bearerToken));
we can use `AUTHENTICATION_AUTHORIZATION_HEADER` here

2019-08-27 18:33 UTC, mediumTaj commented on Connection/WSConnector.cs
> +            Headers.Add("Authorization", Utility.CreateAuthorization(username, password));
we can use `AUTHENTICATION_AUTHORIZATION_HEADER` here

2019-08-27 18:33 UTC, mediumTaj commented on Connection/RESTConnector.cs
> +        public static RESTConnector GetConnector(Authenticator authenticator, string function)
Param is wrong in the comments

2019-08-29 18:44 UTC, merged